language: node_js
node_js:
  - -10
  - -12
  - 10.15.3
  - 12.1.0
cache: npm
jobs:
  include:
    - stage: test
      skip_cleanup: "true"
      script:
        - npm install -g --production coveralls
        - npm run cover
        - npx codecov
        - cat ./build/coverage/lcov.info | coveralls
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        script:
          - npx semantic-release
